### ISSUE TITLE
Error in makePSOCKcluster(names = spec, ...) :    Cluster setup failed. 3 of 3 workers failed to connect. using RegParallel

### ISSUE THREAD

**Issue by jcroft100** [kevinblighe/RegParallel#3]
Hi, Im trying to run your code  for survival analysis via Cox Proportional Hazards regression

﻿https://github.com/kevinblighe/RegParallel#survival-analysis-via-cox-proportional-hazards-regression 

when I run this section of code: 

res5 <- RegParallel(
  data = coxdata,
  formula = 'Surv(Time.RFS, Distant.RFS) ~ [*]',
  FUN = function(formula, data)
    coxph(formula = formula,
          data = data,
          ties = 'breslow',
          singular.ok = TRUE),
  FUNtype = 'coxph',
  variables = colnames(coxdata)[9:ncol(coxdata)],
  blocksize = 2000,
  p.adjust = "BH")

I get the following error:
Error in makePSOCKcluster(names = spec, ...) : 
  Cluster setup failed. 3 of 3 workers failed to connect.

Im using R version 4.0.2 (2020-06-22), r studio Version 1.4.1106 can anyone help?

**Comment by kevinblighe** [comment]
Can you describe the system on which you are running this? Windows?; shared HPC? Please show the output of `sessionInfo()`?

**Comment by kevinblighe** [comment]
No response
